owner: Raznar-Hosting
repo: uptime-monitor-v2
sites: 
  # --- Bare Metals - Nusantara Jakarta ---
  - name: NSTR-JKT1
    url: https://ping-game-nstr-jkt1.raznar-server.uk
    expectedStatusCodes:
      - 200
  - name: NSTR-JKT2
    url: https://ping-game-nstr-jkt2.raznar-server.uk
    expectedStatusCodes:
      - 200

  # --- Our Websites ---
  - name: Main Website
    url: https://raznar.id
    expectedStatusCodes:
      - 200
  - name: Billing Website
    url: https://my.raznar.id
    expectedStatusCodes:
      - 200

  # --- Applications - Jakarta ---
  - name: APP-JKT1
    url: https://app-jkt1.raznar-server.uk:8443
    expectedStatusCodes:
      - 401

  # --- Game General - Jakarta ---
  - name: GNL-JKT1
    url: https://game-gnl-jkt1.raznar-server.uk:8443
    expectedStatusCodes:
      - 401
  - name: GNL-JKT2
    url: https://game-gnl-jkt2.raznar-server.uk:8443
    expectedStatusCodes:
      - 401
  - name: GNL-JKT3
    url: https://game-gnl-jkt3.raznar-server.uk:8443
    expectedStatusCodes:
      - 401
  - name: GNL-JKT4
    url: https://game-gnl-jkt4.raznar-server.uk:8443
    expectedStatusCodes:
      - 401
  - name: GNL-JKT5
    url: https://game-gnl-jkt5.raznar-server.uk:8443
    expectedStatusCodes:
      - 401
  - name: GNL-JKT6
    url: https://game-gnl-jkt6.raznar-server.uk:8443
    expectedStatusCodes:
      - 401

status-website:
  cname: status.raznar.id
  # baseUrl: /uptime-v2
  logoUrl: https://raznar.id/favicon.ico
  favicon: https://raznar.id/favicon.ico
  name: Raznar Uptime Monitor
  introTitle: "**Raznar Hosting Service Status**"
  introMessage: "Live status for our websites, apps, and game servers in Jakarta."
  navbar:
    - title: Status
      href: /
    - title: Website
      href: https://raznar.id
